### ISSUE TITLE
404 on olives-14998738411Ii.jpg 

### ISSUE THREAD

**Issue by Clement83** [OliveTin/DeliciousOlives#1]
Hello,
 I have installed this theme but is not working :( 

![image](https://github.com/OliveTin/DeliciousOlives/assets/7804595/2dc496cf-25b3-49c5-8428-08cd2ee61021)

in config.yml : 

```
# many custom config
themeName: bgui

# more custom config

```

and in chrome devtool : 

![image](https://github.com/OliveTin/DeliciousOlives/assets/7804595/680e1120-5ec3-42f9-9859-b27eebc708b4)

Can you help me please ?

**Comment by jamesread** [comment]
Hey @Clement83 , thanks for reporting this. Sorry - I changed the way theme loading works a while ago and forgot to update this theme. I've just pushed a fix now. 

You can either download it again, or, add `custom-webui/themes/DeliciousOlives/` before the image filename in your theme.css. 

You can see what it should look like in this source file; https://github.com/OliveTin/DeliciousOlives/blob/main/theme.css

**Comment by Clement83** [comment]
its working thank you
